# Generated by Django 5.2.17 on 2026-08-28 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('front_image', models.ImageField(upload_to='inspections/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='inspections/back/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='inspections/side/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('extracted_mrp', models.CharField(blank=True, max_length=100)),
                ('extracted_net_quantity', models.CharField(blank=True, max_length=100)),
                ('extracted_manufacturer', models.TextField(blank=True)),
                ('extracted_date', models.CharField(blank=True, max_length=100)),
                ('extracted_text', models.TextField(blank=True)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('ocr_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
